# Generated by Django 3.2.7 on 2022-01-27 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Squadpoint', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='sport_courts',
        ),
        migrations.AddField(
            model_name='booking',
            name='sport_court',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='Squadpoint.sport_court'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='is_canceled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='is_held',
            field=models.BooleanField(default=False),
        ),
    ]
