# Generated by Django 3.2.7 on 2022-01-27 17:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Squadpoint', '0002_auto_20220127_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='time',
        ),
        migrations.RemoveField(
            model_name='match',
            name='is_canceled',
        ),
        migrations.RemoveField(
            model_name='match',
            name='is_held',
        ),
        migrations.AddField(
            model_name='booking',
            name='ends',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='starts',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
